src/WKTechnology.Application/Models/ErrorViewModel.cs
namespace WKTechnology.Application.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WKTechnology.Application/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using WKTechnology.Application.Contracts;
using WKTechnology.Application.Services.Base;

namespace WKTechnology.Application.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoriaService _categoriaService;

        public CategoriaController(ICategoriaService categoriaService)
        {
            _categoriaService = categoriaService;
        }
        public async Task<ActionResult> Index()
        {
            var categorias = await _categoriaService.GetCategorias();
            return View(categorias);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Categoria categoria)
        {
            try
            {
                await _categoriaService.CreateCategoria(categoria);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var categoria = await _categoriaService.GetCategoria(id);
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Edit(Categoria categoria)
        {
            try
            {
                await _categoriaService.UpdateCategoria(categoria);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _categoriaService.DeleteCategoria(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/WKTechnology.Application/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WKTechnology.Application.Models;

namespace WKTechnology.Application.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WKTechnology.Application/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using WKTechnology.Application.Contracts;
using WKTechnology.Application.Services.Base;

namespace WKTechnology.Application.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoService _produtoService;

        public ProdutoController(IProdutoService produtoService)
        {
            _produtoService = produtoService;
        }
        public async Task<ActionResult> Index()
        {
            var produtos = await _produtoService.GetProdutos();
            return View(produtos);
        }

        public async Task<ActionResult> Create()
        {
            ViewBag.Categorias = await _produtoService.GetCategorias();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Produto produto)
        {
            try
            {
                await _produtoService.CreateProduto(produto);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var produto = await _produtoService.GetProduto(id);
            ViewBag.Categorias = await _produtoService.GetCategorias();
            return View(produto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Edit(Produto produto)
        {
            try
            {
                await _produtoService.UpdateProduto(produto);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _produtoService.DeleteProduto(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/WKTechnology.Application/Views/Categoria/Create.cshtml
@model WKTechnology.Application.Services.Base.Categoria

@{
    ViewData["Title"] = "Nova Categoria";
}

<h4>Nova Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <button type="button" onclick="window.history.back();" value="Voltar" class="btn btn-secondary">
                    Voltar
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WKTechnology.Application/Views/Categoria/Edit.cshtml
@model WKTechnology.Application.Services.Base.Categoria

@{
    ViewData["Title"] = "Editar Categoria";
}

<h4>Editar Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" />
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <button type="button" onclick="window.history.back();" value="Voltar" class="btn btn-secondary">
                    Voltar
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WKTechnology.Application/Views/Categoria/Index.cshtml
@model IEnumerable<WKTechnology.Application.Services.Base.Categoria>

@{
    ViewData["Title"] = "Categorias";
}

<h1>Categorias</h1>

<form asp-action="Create" method="get">
    <button type="submit" class="btn btn-primary">Nova Categoria</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td class="d-flex">
                    <form asp-action="Edit" asp-route-id="@item.Id" method="get">
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </form>                    
                    <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                        <button type="submit" class="btn btn-secondary ms-2">Deletar</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

src/WKTechnology.Application/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "WKTechnology";
}

<div class="text-center">
    <h1 class="display-4">Olá visitante!</h1>
    <p>Utilize o menu para acessar o cadastro de Categorias e Produtos</p>
</div>

src/WKTechnology.Application/Views/Produto/Create.cshtml
@model WKTechnology.Application.Services.Base.Produto

@{
    ViewData["Title"] = "Novo Produto";
}

<h4>Novo Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label class="control-label">Categoria</label>
                <select asp-for="IdCategoria" class="form-control">
                    <option value="">Selecione uma Categoria</option>
                    @foreach (var item in ViewBag.Categorias)
                    {
                        <option value=@item.Value>@item.Text</option>
                    }
                </select>
                <span asp-validation-for="IdCategoria" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <button type="button" onclick="window.history.back();" value="Voltar" class="btn btn-secondary">
                    Voltar
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WKTechnology.Application/Views/Produto/Edit.cshtml
@model WKTechnology.Application.Services.Base.Produto

@{
    ViewData["Title"] = "Editar Produto";
}

<h4>Editar Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" />
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label class="control-label">Categoria</label>
                <select asp-for="IdCategoria" class="form-control">
                    <option value="">Selecione uma Categoria</option>
                    @foreach (var item in ViewBag.Categorias)
                    {
                        <option value=@item.Value>@item.Text</option>
                    }
                </select>
                <span asp-validation-for="IdCategoria" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <button type="button" onclick="window.history.back();" value="Voltar" class="btn btn-secondary">
                    Voltar
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WKTechnology.Application/Views/Produto/Index.cshtml
@model IEnumerable<WKTechnology.Application.Services.Base.Produto>

@{
    ViewData["Title"] = "Produtos";
}

<h1>Produtos</h1>

<form asp-action="Create" method="get">
    <button type="submit" class="btn btn-primary">Novo Produto</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                Categoria
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.Nome)
                </td>
                <td class="d-flex">
                    <form asp-action="Edit" asp-route-id="@item.Id" method="get">
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </form>                    
                    <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                        <button type="submit" class="btn btn-secondary ms-2">Deletar</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

src/WKTechnology.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WKTechnology</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WKTechnology.Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WKTechnology</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-center">
            &copy; 2023 - WKTechnology
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>